// Generated by CoffeeScript 1.9.0
(function() {
  var a, b, c, lightSwitch,
    __slice = [].slice;

  lightSwitch = false;

  if (lightSwitch === false) {
    console.log('Turn on the lights!');
  } else {
    console.log('Turn off the lights!');
  }

  a = 1;

  b = 1 + 1;

  (function() {
    var nums;
    nums = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    nums.forEach(function(n) {
      return result += n;
    });
    return result;
  });

  c = new A();

}).call(this);

//# sourceMappingURL=index.js.map
